// <auto-generated />
using CommandeProduct.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CommandeProduct.Migrations
{
    [DbContext(typeof(CPDbContext))]
    [Migration("20220525175903_ManytoMany")]
    partial class ManytoMany
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CommandeProduct.Models.Client", b =>
                {
                    b.Property<string>("Cin")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClientNom")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LocationPays")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationRue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationVille")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type_C")
                        .HasColumnType("int");

                    b.HasKey("Cin");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("CommandeProduct.Models.Commande", b =>
                {
                    b.Property<int>("Id_Command")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Command"), 1L, 1);

                    b.Property<string>("Cin")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("id_P")
                        .HasColumnType("int");

                    b.HasKey("Id_Command");

                    b.HasIndex("Cin");

                    b.HasIndex("id_P");

                    b.ToTable("Commandes");
                });

            modelBuilder.Entity("CommandeProduct.Models.Produit", b =>
                {
                    b.Property<int>("id_P")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_P"), 1L, 1);

                    b.Property<string>("marque")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nom_P")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("quantite")
                        .HasColumnType("int");

                    b.HasKey("id_P");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("CommandeProduct.Models.Commande", b =>
                {
                    b.HasOne("CommandeProduct.Models.Client", "client")
                        .WithMany("Commande")
                        .HasForeignKey("Cin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CommandeProduct.Models.Produit", "produit")
                        .WithMany("Commande")
                        .HasForeignKey("id_P")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("client");

                    b.Navigation("produit");
                });

            modelBuilder.Entity("CommandeProduct.Models.Client", b =>
                {
                    b.Navigation("Commande");
                });

            modelBuilder.Entity("CommandeProduct.Models.Produit", b =>
                {
                    b.Navigation("Commande");
                });
#pragma warning restore 612, 618
        }
    }
}
